/**
 * Integration tests — run against the real application.
 * Prerequisite: `npm run dev` (Docker stack) must be running.
 *
 * Fixture files are in tests/fixtures/ and were generated by tests/fixtures/create.ts.
 * sample.epub  → "Python Fundamentals" by "Jane Smith", 3 chapters, python detected
 * sample.pdf   → same metadata, delivered as PDF (triggers isPdfUpload warning)
 * corrupted.epub → .epub extension, invalid content (causes server 500)
 */

import { test, expect, type Page } from '@playwright/test'
import path from 'path'
import { fileURLToPath } from 'url'

const FIXTURES = path.join(path.dirname(fileURLToPath(import.meta.url)), '../fixtures')
const EPUB = path.join(FIXTURES, 'sample.epub')
const PDF  = path.join(FIXTURES, 'sample.pdf')
const CORRUPTED = path.join(FIXTURES, 'corrupted.epub')

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function uploadFile(page: Page, filePath: string) {
  await page.locator('input[type=file]').setInputFiles(filePath)
}

// ─── Idle state ───────────────────────────────────────────────────────────────

test('shows upload zone with heading and hint text', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Book to Video' })).toBeVisible()
  await expect(page.getByRole('button', { name: /upload epub or pdf/i })).toBeVisible()
  await expect(page.getByText(/drop an epub or pdf file/i)).toBeVisible()
  await expect(page.getByText('.epub or .pdf — EPUB preferred')).toBeVisible()
})

// ─── Client-side validation (no server call) ──────────────────────────────────

test('rejects non-EPUB/PDF files before hitting the server', async ({ page }) => {
  await page.goto('/')
  await page.locator('input[type=file]').setInputFiles({
    name: 'notes.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('plain text'),
  })
  await expect(page.getByText('Only EPUB or PDF files are accepted')).toBeVisible()
  // Error is shown instantly — spinner must NOT appear
  await expect(page.getByText(/parsing epub/i)).not.toBeVisible()
})

// ─── EPUB happy path ──────────────────────────────────────────────────────────

// These tests share the same book record; run serially to avoid DB race conditions.
test.describe.serial('EPUB upload', () => {
  test.setTimeout(60_000) // LLM call can take up to ~15 s

  test('shows loading spinner while the server is processing', async ({ page }) => {
    await page.goto('/')
    const fileInput = page.locator('input[type=file]')
    await fileInput.setInputFiles(EPUB)
    // Spinner must appear before the result arrives
    await expect(page.getByText(/parsing epub/i)).toBeVisible()
    // Wait for the result
    await expect(page.getByRole('heading', { name: 'Python Fundamentals' })).toBeVisible({ timeout: 45_000 })
  })

  test('renders the correct title and author', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByRole('heading', { name: 'Python Fundamentals' })).toBeVisible({ timeout: 45_000 })
    await expect(page.getByText('Jane Smith')).toBeVisible()
  })

  test('renders all three chapters in order', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('3 chapters')).toBeVisible({ timeout: 45_000 })

    const items = page.locator('ol li')
    await expect(items).toHaveCount(3)
    await expect(items.nth(0)).toContainText('Introduction to Python')
    await expect(items.nth(1)).toContainText('Variables and Data Types')
    await expect(items.nth(2)).toContainText('Functions and Modules')
  })

  test('detects Python as a primary language', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('Python Fundamentals')).toBeVisible({ timeout: 45_000 })
    await expect(page.getByText('python')).toBeVisible()
  })

  test('LLM assigns a valid prerequisite level badge', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('Python Fundamentals')).toBeVisible({ timeout: 45_000 })
    const badge = page.locator('span').filter({ hasText: /^(beginner|intermediate|advanced|unknown)$/ })
    await expect(badge).toBeVisible()
  })

  test('LLM extracts at least one key concept', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('Python Fundamentals')).toBeVisible({ timeout: 45_000 })
    await expect(page.getByText(/key concepts/i)).toBeVisible()
    // At least one concept chip must exist
    const concepts = page.locator('div').filter({ hasText: /key concepts/i }).locator('span')
    await expect(concepts.first()).toBeVisible()
  })

  test('"Upload a different book" resets to the idle upload zone', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('Python Fundamentals')).toBeVisible({ timeout: 45_000 })
    await page.getByRole('button', { name: /upload a different book/i }).click()
    await expect(page.getByRole('button', { name: /upload epub or pdf/i })).toBeVisible()
    await expect(page.getByText('Python Fundamentals')).not.toBeVisible()
  })
})

// ─── PDF upload ───────────────────────────────────────────────────────────────

test.describe.serial('PDF upload', () => {
  test.setTimeout(60_000)

  test('shows the PDF best-effort warning banner', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, PDF)
    await expect(
      page.getByText(/pdf uploaded.*code block detection is best-effort/i),
    ).toBeVisible({ timeout: 45_000 })
  })

  test('still renders book title and chapters alongside the warning', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, PDF)
    await expect(page.getByText(/pdf uploaded/i)).toBeVisible({ timeout: 45_000 })
    // Title comes from the PDF Info dictionary
    await expect(page.getByRole('heading', { name: 'Python Fundamentals' })).toBeVisible()
    // At least one chapter was detected (or page-fallback was used)
    const chapterCount = page.getByText(/\d+ chapters?/)
    await expect(chapterCount).toBeVisible()
  })
})

// ─── Duplicate upload ─────────────────────────────────────────────────────────

test.describe.serial('Duplicate upload', () => {
  test.setTimeout(90_000)

  test('shows "already in the library" note on a second upload of the same book', async ({ page }) => {
    // First upload (may already exist from the EPUB suite above — that's fine)
    await page.goto('/')
    await uploadFile(page, EPUB)
    await expect(page.getByText('Python Fundamentals')).toBeVisible({ timeout: 45_000 })

    // Reset and upload again
    await page.getByRole('button', { name: /upload a different book/i }).click()
    await uploadFile(page, EPUB)
    await expect(page.getByText(/already in the library/i)).toBeVisible({ timeout: 45_000 })
  })
})

// ─── Error states ─────────────────────────────────────────────────────────────

test.describe('Error states', () => {
  test('shows a server error for a corrupted EPUB', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, CORRUPTED)
    // Server returns 500 — error message must appear
    const errorBox = page.locator('.border-red-200, .border-red-800')
    await expect(errorBox).toBeVisible({ timeout: 15_000 })
  })

  test('"Try again" button returns to the idle upload zone after an error', async ({ page }) => {
    await page.goto('/')
    await uploadFile(page, CORRUPTED)
    const errorBox = page.locator('.border-red-200, .border-red-800')
    await expect(errorBox).toBeVisible({ timeout: 15_000 })

    await page.getByRole('button', { name: /try again/i }).click()
    await expect(page.getByRole('button', { name: /upload epub or pdf/i })).toBeVisible()
  })
})
